cache:
  directories:
   - .cache
   - deps/node_modules/puppeteer/.local-chromium
   - $HOME/.propel/cache
branches:
  only:
  - master
language: node_js
os:
- linux
# - osx -- disabled because of Travis CI downtime/backlog
git:
  submodules_depth: 1
node_js:
- '8.8'
install: echo "Intentionally skipping npm install."
script:
- npm rebuild puppeteer
- ./tools/presubmit.js
