language: node_js
node_js:
- '8.8'
script:
- ./deps/cpplint/cpplint.py *.cc
- npm install .
- node ./node_modules/webpack/bin/webpack.js
- ./node_modules/typescript/bin/tsc
- node dist/backprop_test.js
- node dist/tensor_test.js
- node dist/util_test.js
- node test-tensorflow-binding.js
